name: vaxtrack
description: "VaxTrack is your all-in-one family vaccination companion, offering seamless profile management, easy clinic discovery, and convenient appointment scheduling, all while keeping your vaccination history and essential info at your fingertips."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
